### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by samjrholt** [ubermag/ubermag#106]
Hi! 

I've downloaded ubermag on my windows 10 PC on Anaconda as per the installation instructions. The installation test reported no errors. I can load all of the modules I require and set the regions, mesh, energy etc with no problem at all but I can't seem to drive the system. Any ideas would be very helpful!

Error:
![image](https://user-images.githubusercontent.com/48217392/86411550-022fa200-bcb5-11ea-9232-80ddfee587ac.png)

**Comment by catrevil** [comment]
I think you should post this in [ubermag/help](https://github.com/ubermag/help), and someone will move this there hopefully somehow. I’m not keen on that functionality.

I digress—do you have Docker installed? If not, install this. It is free.

It seems to me that you are calling for a functionality (boundary conditions or a special crystallographic lattice) which does not parse out well or at all within the Windows OS. To overcome this, a small lightweight Linux machine can be pulled from the cloud via Docker to run that portion of the code with the more expansive boundary conditions & lattices which they have implemented. Marijan recently implemented this, and this will be present in the recent updates which you may have pulled.

FYI: The first run of the Docker specific code will require the image to be pulled down, but once this is completed the overhead is negligible.

**Comment by marijanbeg** [comment]
Hi @samjrholt, thank you for your question. From the error message you get, I assume you are using probably using DMI and/or periodic boundary conditions. This is an intrinsic limitation of OOMMF because it does not support that. However, we wrote some extensions to enable that functionality. Unfortunately, there is no way of including those extensions on Windows as a part of conda installation (on MacOS and Linux this is enabled).

As @catrevil said (thank you for addressing this), you can use docker (https://www.docker.com/products/docker-desktop), which would run in the background and enable those extensions. For more details, you can have a look at the last comment in this issue: https://github.com/ubermag/workshop/issues/15.

I hope this helps. If not, please let us know and reopen this issue.

Best,
Marijan

**Comment by samjrholt** [comment]
Thank you both very much! It is all working now.

**Comment by marijanbeg** [comment]
Hi @samjrholt, great, thank you for letting us know.
